version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.1
jobs:
  coverage:
    steps:
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  node-tests:
    jobs:
      - node/test
      - coverage
